import { create } from "storybook/theming/create";

export default create({
  base: "dark",
  brandTitle: "Luck · Design system WL3",
  brandImage: "./wl3-horizontal-dark.svg",
  brandUrl: "https://github.com/welllucky/luck",
  brandTarget: "_self",
  colorPrimary: "#F5B301",
  colorSecondary: "#F5B301",
  appBg: "#111110",
  appContentBg: "#1A1A18",
  appPreviewBg: "#111110",
  appBorderColor: "rgba(255,255,255,.08)",
  appBorderRadius: 6,
  fontBase: "'Manrope', system-ui, sans-serif",
  fontCode: "'JetBrains Mono', ui-monospace, monospace",
  textColor: "#F4F4F2",
  textMutedColor: "#9C9C98",
  textInverseColor: "#111110",
  barTextColor: "#9C9C98",
  barSelectedColor: "#F5B301",
  barHoverColor: "#FFCB3D",
  barBg: "#1A1A18",
  inputBg: "#0C0C0B",
  inputBorder: "rgba(255,255,255,.18)",
  inputTextColor: "#F4F4F2",
  inputBorderRadius: 4,
});
